MODEL:
  META_ARCHITECTURE: "SimpleBaseline"
  WEIGHTS: "torchvision-R-101.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res5"]
    RES5_DILATION: 2
  ROI_HEADS:
    IN_FEATURES: ["res5"]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.00001
  STEPS: (120000, 180000)
  MAX_ITER: 210000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 500
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
SEED: 40244023
INPUT:
  MIN_SIZE_TRAIN: (448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 608
  MAX_SIZE_TEST: 1024
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 0
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
  ASPECT_RATIO_GROUPING: False
VERSION: 2
