_BASE_: "Base-SimpleBaseline.yaml"
MODEL:
  WEIGHTS: "torchvision-R-101.pkl"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res5"]
    RES5_DILATION: 2
  ROI_HEADS:
    IN_FEATURES: ["res5"]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  SimpleBaseline:
    NUM_QUERIES: 72
    NUM_CLASSES: 30
    HIDDEN_DIM: 384
    BOX_JIT: True
    BOX_JIT_RATIO: 0.05
DATASETS:
  TRAIN: ("vid_train_15chunks", "det")
  TEST:  ("vid_val_part0",)
SOLVER:
  STEPS: (120000, 180000)
  MAX_ITER: 210000
  IMS_PER_BATCH: 4
  BASE_LR: 0.00001
  WARMUP_ITERS: 500
INPUT:
  MIN_SIZE_TRAIN: (448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 608
  MAX_SIZE_TEST: 1024
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 0
